export declare enum PlayerEventTypes {
    PLAYAPP_USER_HEARTBEAT = "PLAYAPP_USER_HEARTBEAT",
    PLAYER_CAST_SPELL = "PLAYER_CAST_SPELL",
    PLAYER_JOINED_MINECRAFT_SERVER = "PLAYER_JOINED_MINECRAFT_SERVER",
    PLAYER_JOINED_WORLD = "PLAYER_JOINED_WORLD",
    PLAYER_LOCATION_HEARTBEAT = "PLAYER_LOCATION_HEARTBEAT",
    PLAYER_QUIT_MINECRAFT_SERVER = "PLAYER_QUIT_MINECRAFT_SERVER",
    PLAYER_UPDATED_MINECRAFT_LOCALE = "PLAYER_UPDATED_MINECRAFT_LOCALE",
    PLAYER_UPSERT_LORE = "PLAYER_UPSERT_LORE",
    PLAYER_WAS_AT = "PLAYER_WAS_AT",
}
