export declare enum PlayerEventTypes {
    PLAYAPP_USER_HEARTBEAT = "PLAYAPP_USER_HEARTBEAT",
    PLAYER_JOINED_MINECRAFT_SERVER = "PLAYER_JOINED_MINECRAFT_SERVER",
    PLAYER_QUIT_MINECRAFT_SERVER = "PLAYER_QUIT_MINECRAFT_SERVER",
    PLAYER_UPSERT_LORE = "PLAYER_UPSERT_LORE",
    PLAYER_FOUND_SCROLL = "PLAYER_FOUND_SCROLL",
    PLAYER_CAST_SPELL = "PLAYER_CAST_SPELL",
    PLAYER_WAS_AT = "PLAYER_WAS_AT",
    PLAYER_JOINED_WORLD = "PLAYER_JOINED_WORLD",
}
