// export enum PlayerEventTypes {
//     PLAYAPPUSERHEARTBEAT,
//     PLAYER_JOINED_MINECRAFT_SERVER,
//     PLAYER_QUIT_MINECRAFT_SERVER,
//     PLAYER_UPSERT_LORE,
//     PLAYER_CAST_SPELL,
//     PLAYER_WAS_AT,
// }

export interface PlayerEventTypes {
    PLAYAPPUSERHEARTBEAT: string,
    PLAYER_JOINED_MINECRAFT_SERVER: string,
    PLAYER_QUIT_MINECRAFT_SERVER: string,
    PLAYER_UPSERT_LORE: string,
    PLAYER_CAST_SPELL: string,
    PLAYER_WAS_AT: string,
}